### ISSUE TITLE
Hiera usage (ldap/client)

### ISSUE THREAD

**Issue by linuxmail** [djjudas21/puppet-freeradius#108]
hi,

I just want to ask, of there is any plan for Hiera support. I tried to configure for example the LDAP module, like

```
freeradius::module::ldap: 'ensure'
freeradius::module::ldap::identity: 'cn=webadmin,ou=Accounts,dc=example,dc=com'
freeradius::module::ldap::password: 'secret'
freeradius::module::ldap::basedn: 'ou=People,dc=example,dc=com'
```
but it seems not working. So either I calling the class wrong, or it won't work with Hiera, so I have to create a profile class.

Any suggestions ?

**Comment by djjudas21** [comment]
Unfortunately I changed jobs and I no longer use this module in my new job, so there are no plans for further development. However I am happy to curate the code and accept PRs, etc.

From memory, without testing: the Hiera data you have provided is for a class, not a defined type (i.e. you can have multiple instances of the `ldap` module). I always used this module without Hiera, just using a profile class. You may be able to abstract the profile class with Hiera.

If you make any changes to this module to improve Hiera support, it would be excellent if you could share them back here :smile:
