### ISSUE TITLE
home_server_pool undefined method `each' for "xxx":String

### ISSUE THREAD

**Issue by roumano** [djjudas21/puppet-freeradius#110]
When i try to use the ressources home_server_pool via a very simple configuration : 

```
  freeradius::home_server { "localhost":
    secret => 'xxxx',
    ipaddr => '127.0.0.1',
  }

  freeradius::home_server_pool { "my_auth_failover":
    home_server => 'localhost',
  }
```

I got a error : 

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template freeradius/home_server_pool.erb:
  Filepath: /etc/puppet/code/environments/radius/modules/freeradius/templates/home_server_pool.erb
  Line: 6
  Detail: undefined method `each' for "localhost":String
 at /etc/puppet/code/environments/radius/modules/freeradius/manifests/home_server_pool.pp:18:16
```

I'm not a puppet expert but it's look like, the file templates/home_server_pool.erb need a small change to work as expected : 
```
diff templates/home_server_pool.erb templates/home_server_pool.erb.old 
6,7c6,7
< <% if defined?(@home_server) -%>
< 	home_server = <%= @home_server %>
---
> <% @home_server.each do |server| -%>
> 	home_server = <%= server %>
```

**Comment by djjudas21** [comment]
Hmm, I think `home_server_pool` expects >1 `home_server` in an array. Exactly 1 `home_server` is still valid, though.

Your proposed change will make it work for your case of 1 `home_server` but break for >1. Please could you try passing in your single `home_server` as an array? The template should then loop on a single value. If this works, I'll make a note in the docs and also consider writing some code that will flip a string to an array if necessary.

```puppet
  freeradius::home_server_pool { "my_auth_failover":
    home_server => ['localhost'],
  }
```

**Comment by roumano** [comment]
Sorry for my mistake ...

**Comment by djjudas21** [comment]
No worries, glad it's working for you now. I've slightly improved the documentation in 472b073
