### ISSUE TITLE
freeradius::module::ldap multiple server

### ISSUE THREAD

**Issue by roumano** [djjudas21/puppet-freeradius#112]
The syntax of ldap configuration have been change in freeradius , i got this warning when i start the daemin in debug mode :  

```
Listing multiple LDAP servers in the 'server' configuration item is deprecated and will be removed in a future release.  Use multiple 'server' configuration items instead
- server = 'ldap1,ldap2'
+ server = 'ldap1'
+ server = 'ldap2'
```

Can you update the resource freeradius::module::ldap to follow this ?

**Comment by djjudas21** [comment]
I'm not using this module at the moment so I can't actually test, but it looks like this exception is already handled in the code:

```puppet
# manifests/module/ldap.pp

  $serverarray = any2array($server)
  unless is_array($serverarray) {
    fail('$server must be an array of hostnames or IP addresses')
  }

  # FR3.0 format server = 'ldap1.example.com, ldap1.example.com, ldap1.example.com'
  # FR3.1 format server = 'ldap1.example.com'
  #              server = 'ldap2.example.com'
  #              server = 'ldap3.example.com'
  $serverconcatarray = $::freeradius_version ? {
    /^3\.0\./ => any2array(join($serverarray, ',')),
    default   => $serverarray,
  }
```

Can you please confirm which version of FreeRADIUS you are running, and also what the fact `$::freeradius_version` resolves to on your system?

**Comment by djjudas21** [comment]
Ah, I think this must be because the Debian maintainers have backported bugfixes & features from 3.1.x to 3.0.x. You wouldn’t have this problem if you built your 3.0.12 from upstream sources.

So there’s not much we can do about this. Luckily it’s only a warning and doesn’t actually break anything, so you are safe to ignore the warning.
