### ISSUE TITLE
Client firewall rule is repeatedly added to iptables INPUT chain

### ISSUE THREAD

**Issue by guest715** [djjudas21/puppet-freeradius#121]
When setting firewall to true for a client resource, the rule is repeatedly added to the iptables INPUT chain for each Puppet run. The problem appears to be with lines 61 and 68 in client.pp. The hyphen that follows the 100 i.e. 100**-**${shortname} needs to be replaced with a space in order for the Firewall resource to be able to match the rule on subsequent Puppet runs after it has been added to the iptables INPUT chain.

**Comment by djjudas21** [comment]
Hi there, thanks for reporting. I'm not actively using this module at the moment so I don't have the ability to dev/test it. If you could put together a pull request I'd be happy to accept it though - thanks.

**Comment by djjudas21** [comment]
From what I remember of using this module (originally written for Puppet 3), spaces were not allowed in firewall rule names, hence the hyphen. I wonder if this has now changed?

**Comment by guest715** [comment]
Hi @djjudas21, I think lines 196 to 211, particularly line 210, of the puppetlabs firewall resource (https://github.com/puppetlabs/puppetlabs-firewall/blob/master/lib/puppet/type/firewall.rb) confirms your suspicion.

**Comment by guest715** [comment]
Hi @djjudas21, I've created Pull request #122 to address this issue. Unfortunately I wasn't able to get Bundle to resolve Gem dependencies within my Windows development environment so I wasn't able to run the spec tests but I did review them and don't think the changes in #122 will cause any failures.

**Comment by djjudas21** [comment]
Thanks a lot. I've accepted & merged. Do you need a tagged release for this too, or are you running from git?

**Comment by guest715** [comment]
Thanks @djjudas21. I’m running from Puppet Forge so if you could also release a new version that would be very appreciated.

**Comment by djjudas21** [comment]
No problem. I've tagged release v3.8.2 in Git but at the moment I'm struggling to actually build a Puppet module for the Forge on my new work PC, so I'll do that at home later on :+1:

**Comment by guest715** [comment]
Thanks @djjudas21, I appreciate all your assistance.
