### ISSUE TITLE
Please release 3.8.2 to puppetforge

### ISSUE THREAD

**Issue by davidc** [djjudas21/puppet-freeradius#127]
Latest on puppet forge is 3.8.1 which doesn't support Debian 10

Thanks!

**Comment by jgazeleyfr** [comment]
Thanks for the reminder. I've just tried to build this for Puppet Forge in the same way as always, but the build is failing, not sure if something has changed. Does it do this for you too?

```
[jonathan@hephaestos puppet-freeradius]$ puppet module build
Warning: `puppet module build` is deprecated and will be removed in a future release. This action has been replaced by Puppet Development Kit. For more information visit https://puppet.com/docs/pdk/latest/pdk.html.
   (location: /usr/share/ruby/vendor_ruby/puppet/face/module/build.rb:56:in `block (3 levels) in <top (required)>')
Error: undefined method `delete' for #<JSON::Ext::Generator::State:0x00005618321940d8>
Error: Try 'puppet help module build' for usage
```

**Comment by djjudas21** [comment]
Well apparently I commented with my work GitHub account but it still is me, albeit with a more recent, fatter profile pic ;)

**Comment by djjudas21** [comment]
OK, I converted the module to PDK so I can build it that way, which works, but it can't currently be uploaded to Puppet Forge due to invalid dependency versions. I've gotta finish for the day now but I'll come back to this and update the deps.

**Comment by djjudas21** [comment]
I have now uploaded 3.8.2 to the Forge. Sorry for the delay :+1:
