### ISSUE TITLE
Integer data type too restrictive for firewall port

### ISSUE THREAD

**Issue by decibelhertz** [djjudas21/puppet-freeradius#136]
https://github.com/djjudas21/puppet-freeradius/blob/master/manifests/client.pp#L19 requires an integer, but I would like to use the string `'1812-1813` or array `[1812,1813]`, which is valid for passing along to the firewall resource.  Can you consider using `Variant[Array[Integer],Integer]`?

**Comment by djjudas21** [comment]
Thanks for this. Yes those ranges are valid for firewall rules and it's a good suggestion. Can you raise a PR, please?

**Comment by nward** [comment]
Hi @decibelhertz I want to close this one off - are you OK if I raise the PR to fix this, or do you have one you can fire through?

**Comment by decibelhertz** [comment]
Yes.  I've been sidetracked on this matter and would be happy for help
