### ISSUE TITLE
Duplicate logrotate configs

### ISSUE THREAD

**Issue by sts** [djjudas21/puppet-freeradius#143]
Dist: Debian/Buster
Package: freeradius
Version: 3.0.17+dfsg-1.1

Logrotate fails with the following error, since the package distributed logrotate config and the puppet module config have duplicate definitions for radius log files:

```
logrotate[27780]: error: freeradius:18 duplicate log entry for /var/log/freeradius/checkrad.log
logrotate[27780]: error: found error in file freeradius, skipping
logrotate[27780]: error: radiusd:4 duplicate log entry for /var/log/freeradius/radius.log
logrotate[27780]: error: found error in file radiusd, skipping
systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by nward** [comment]
Hi @sts can you share the content of the logrotate configs you get from the package and from the puppet module, to show the exact issue?

Keen to sort this but I don't have immediate access to a Debian box at the minute.

**Comment by nward** [comment]
@sts Can you please comment with further info if this issue still exists? Closing for now.
