### ISSUE TITLE
Call for Maintainers!

### ISSUE THREAD

**Issue by djjudas21** [djjudas21/puppet-freeradius#147]
This project has been a bit unloved since I switched jobs in 2018 and stopped using this FreeRADIUS Puppet module in production. Since then I've been happy to accept pull requests and release new versions, but it's becoming clear that the module could do with a new maintainer - someone who actually uses the module.

I have started conversations with [Vox Pupuli](https://forge.puppet.com/puppet), the Puppet community group who maintain third-party modules about taking ownership but I also wanted to shout out to everyone who has forked or contributed to this code already in case anyone wants to help with maintenance:

@amateo @steadramon @sts @deligatedgeek @diranged @nward @coreone @rogermartensson @JonTheNiceGuy @OlivierLM @guest715 @ardrigh @mrobbert @geoffdavis @davidc @infracaninophile @carlgarner @starryparrot @craigwatson @treydock @pioto @rotanid @theosotr @ihpu @raphink @davidc0le @paulseward @bhechinger @BrandwatchLtd @broadinstitute @ceesco53 @chihoko @chris-gibbs @claranet @ConclusionMC @cwmoller @dabelenda @decibelhertz @djfraggle @eniuz @gwdg @hihiuztrewq @janit42 @krobertson @Lavaburn @mlosapio @pikseluls @riseops @ross-w @roumano @SearchLightNZ @sklemer1 @sohonet @SuPair @zennoc @zivis

Sorry for the mass tagging... feel free to unwatch this issue if you're not interested. Thanks! :smile:

**Comment by djjudas21** [comment]
See also #131

**Comment by amateo** [comment]
Hi @djjudas21,

I could help, but I can't guarrantee to response quickly.

**Comment by nward** [comment]
I would be open to helping with this as I’m using radius (a lot!) in production deployed with puppet, so this is sort of my day job anyway :)

**Comment by steadramon** [comment]
Sorry cannot commit much time to this - will continue to submit PRs for things that can be easily fixed though!

**Comment by djjudas21** [comment]
Thanks @steadramon, understood. We're grateful for any PRs you can submit.

@nward and @amateo thanks for volunteering - I will grant you "maintainer" status on this project. I guess we should have some way of communicating with each other about project direction and specific PRs, plus at the moment it will still need to be me who publishes new releases to Puppet Forge.

**Comment by nward** [comment]
Thanks :-)

I think for specific PRs, the general discussion on the PR page works I think.
Perhaps an email discussion re. direction is a good idea? As owner can you see my email address or anything? I am in NZDT (UTC+13).

I had a look over the weekend and have 4 or 5 PR-able bits since my 3.0.21 update a few months ago - mostly cleaning some things up, and I added a class to manage radsniff (RedHat only at this stage). I have also got to finalise #142 

I'd like to do go through and do big chunk of linter type fix ups - remove newlines at end of lines, breaking up long lines, all that stuff. `pdk validate` has a hard time with the spec files - which is almost certainly my fault from when I reworked the tests...

**Comment by djjudas21** [comment]
@nward No, I don't have any info other than what I could already see on your Github profile. Although I think I see your email address in the git commit logs. I'll drop you a message to verify.

**Comment by amateo** [comment]
Hi,

I have just accepted the invitation to the project. I guess you could get my email from my commits too.

**Comment by djjudas21** [comment]
Thanks @amateo. I've dropped you an email.

I'm gonna close this issue now, but if anyone wants to join as a collaborator then just tag me :+1:
