### ISSUE TITLE
Release.. v4?

### ISSUE THREAD

**Issue by nward** [djjudas21/puppet-freeradius#156]
I'm proposing a new release major version 4 - to signal that there are some breaking changes (which I think there are).

I'd like to create a milestone for it, and tag a couple of issues (and maybe create some issues) which can be part of that milestone, then we have a goal to work towards.

I think we can leave this issue open as a way to track any general discussion on v4 (if that's what we agree it should be called, if not we can rename this to something else).

**Comment by amateo** [comment]
Ok. What are the changes you are planning to achieve with this new version?

**Comment by nward** [comment]
Well, mostly a new release so people can use the changes we have done in the last 6 months or so, reworking some things and updating the module a lot. Suggesting v4 as there are (I think) some breaking changes.

**Comment by amateo** [comment]
Ah... I thought you wanted to deploy a code refactor or implement new features.

I agree with v4.

**Comment by nward** [comment]
Nope! Just thinking what else we want to get done before we do a v4 - I see there's a few issues and a merge request, and I think I have a couple of things I haven't pushed yet. Will review those and push if useful.

**Comment by djjudas21** [comment]
Yep I'm happy with tagging the release as v4 as there definitely are significant changes to the codebase. And I'm happy to use milestones or anything else to ease collaboration, now this is a multiplayer project :smile:

**Comment by djjudas21** [comment]
One thing I'm not sure about is when publishing modules on Puppet Forge. Currently it's tied to my personal account `jgazeley` and in the past I've always `puppet module build` and uploaded the tarball manually - but it looks like you can create API keys these days, so I'll create one we can use in a CI pipeline etc to publish new builds.

**Comment by nward** [comment]
Awesome. I've created the version 4 milestone, and spammed a few other PRs with changes I've got running on my local copy.

The API key to push to puppet forge thing sounds pretty useful - I think we found some GitHub actions that implemented the actual work for us, right? Might be worth digging those up.
I don't think we'll really ever be in a place where @amateo or myself need to push a release to puppet forge, though, so I don't think you need to put any huge urgency behind it if you're happy to do it manually every now and then.
(though I love automating stuff like that so purely from a cool tech POV, I'm on board!)

**Comment by djjudas21** [comment]
Just picking this up again. It's been over 2 years since I/we last tagged a release, and there are [loads of commits that are not in a release](https://github.com/djjudas21/puppet-freeradius/compare/3.9.2...main).

I know we haven't yet checked off everything on the [v4 milestone](https://github.com/djjudas21/puppet-freeradius/milestone/1) but I think we need to get some of this work released. Any thoughts on whether we can get v4 ready quickly, or just release now as is, and push the rest of the improvements back to v4.1?

**Comment by deligatedgeek** [comment]
The first 2 of the open [v4 milestone](https://github.com/djjudas21/puppet-freeradius/milestone/1) issues have commits, 1 is this conversation, and maybe [Move params logic to hiera data](https://github.com/djjudas21/puppet-freeradius/issues/162) could wait till 4.1

**Comment by nward** [comment]
3 of those issues are code related, one is just this one. I can get those other 3 squared away - I wanted some feedback on #162 before I charged ahead with it. From memory I have most of the code completed for that so if we are OK with what I mentioned I can push that.

For v4 I'd also like to add support for FR3.2 which is being released soon - I'll can get that (and the others) done by next week.

For #160 I think it was previously approved then I pushed some other fixes and it un-approved :-)

**Comment by djjudas21** [comment]
Thanks for the update @nward. I've just re-approved #160

**Comment by CaptainMalu** [comment]
Any news about v4?
With 3.9.2 we get now trouble on rocky8 machines.

**Comment by nward** [comment]
I think we should do a V4 shortly once the flurry of activity a the moment has settled, @djjudas21.

I'd like to do a V5 subsequently with the changes for #184 as that may likely be fairly impacting.

**Comment by anthonysomerset** [comment]
please can we consider a release soon :) at the very least puppet 8 support :)

**Comment by djjudas21** [comment]
@anthonysomerset Yes, I think we can do a release soon. Sorry it has taken so long.

@nward When we last spoke about this we were waiting for a bunch of PRs to get merged. Some of these are still outstanding, but I think there is sufficient urgency to get a release out that works on Puppet 8 and fixes behaviour on RHEL 8 that I want to push ahead, there being no objections. Do you need/want to do any testing work before I tag and publish a new release?

**Comment by nward** [comment]
No issue doing that. I've just sent a PR #219 which will fix the issues on #217 which we can then merge.. are there any other critical things we want to address?

**Comment by djjudas21** [comment]
It's great that the tests are now passing cleanly on `main`. I think it's important we get this release out ASAP because people are waiting on various compatibility fixes etc. We can always follow it up with a second release shortly after, if there are more PRs to merge.

**Comment by djjudas21** [comment]
v4 has now been published on GitHub and Puppet Forge, with an extensive changelog. Thanks everyone for your contributions!

* https://github.com/djjudas21/puppet-freeradius/releases/tag/4.0.0
* https://forge.puppet.com/modules/jgazeley/freeradius/readme
