### ISSUE TITLE
Rename "master" to "main"

### ISSUE THREAD

**Issue by nward** [djjudas21/puppet-freeradius#161]
Proposing we use "main" as the primary branch, rather than "master". While I absolutely agree with the cultural reasons for this, I'm proposing this more because this is going with the flow of the industry.

PDK was updated to expect the git main branch to be "main". This is configurable, but having custom config in there for each instance this comes up feels like we'll be paddling against the flow.

I don't think this would a significant change - we would update any PRs in flight (and all but one are mine so fine by me!).

**Comment by amateo** [comment]
Agree

**Comment by djjudas21** [comment]
Sorry, was offline yesterday :slightly_smiling_face: Yes I think this change is good both from cultural and technical reasons.

**Comment by nward** [comment]
Awesome!

@djjudas21 I think you're the only one that can do this.

Info is here: https://github.com/github/renaming

It's fairly clean by the looks - updates any PRs, and does HTTP 301s etc.
I've done it on my fork, but it's obviously not as interesting. If I push to my fork's `master` it gives me this:
```
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/SearchLightNZ/puppet-freeradius/pull/new/master
remote:
remote: Heads up! The branch 'master' that you pushed to was renamed to 'main'.
```

Once we have done this I can lock in the tests etc. for #159 :-)

**Comment by djjudas21** [comment]
Excellent. I'll do this now

**Comment by djjudas21** [comment]
Done.

>Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share these commands:

```
git branch -m master <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
```
