### ISSUE TITLE
detail module template has the same error as FreeRADIUS example

### ISSUE THREAD

**Issue by deligatedgeek** [djjudas21/puppet-freeradius#171]
I have recently moved to the main branch of the puppet-freeradius module and freeradius failed to start after puppet ran.  The issue was created by this commit https://github.com/djjudas21/puppet-freeradius/commit/d857d6201b7ff93b4d7aa1ef2ccdd4fc2071ce6c, when the detail.erb template was updated to be the same as the detail example file in freeradius, which doesn't work because freeradius requires each module to be named and [detail](https://github.com/FreeRADIUS/freeradius-server/blob/bef190c8da06716b871e2fbc4bdf5377b85bfc4b/raddb/mods-available/detail#L21) doesn't contain one.  The detail.log example file does contain a name.

I can create a PR for this

**Comment by djjudas21** [comment]
Thanks, please do. Thanks for your vigilance

**Comment by nward** [comment]
That's embarrassing! Sounds great. Maybe you can write some tests to detect that issue as well so it or something like it doesn't happen again? I don't think we have specs for `freeradius::module::detail`.

**Comment by deligatedgeek** [comment]
This resolved the issue.
