### ISSUE TITLE
Rework manifests to enable OS-independent testing

### ISSUE THREAD

**Issue by nward** [djjudas21/puppet-freeradius#183]
The manifests currently reference files by their full name, which makes creating specs difficult. Instead, the name should be generic, and have a path attribute, for example:

```
file { "${fr_moduleconfigpath}/attr_filter/${name}":
```

should be:
```
file { "freeradius attr_filter ${name}":
   path => "${fr_moduleconfigpath}/attr_filter/${name}",
```

Similarly, systemd units, etc. which differ per-OS should use a common name regardless of OS.

Currently, all the specs assume redhat, so only redhat is fully tested.

(I am currently working on this and testing in my environment, PR to come this week)

**Comment by djjudas21** [comment]
I think this is sensible. I only started out omitting `path` and setting the path in the name of the object for brevity, back in the Puppet 0.2.6 days. I think this is a very good reason to revisit that.
