### ISSUE TITLE
Syntax Error in params.pp

### ISSUE THREAD

**Issue by hihiuztrewq** [djjudas21/puppet-freeradius#228]
In params.pp 2 $ signs are missing (before "facts"). 

https://github.com/djjudas21/puppet-freeradius/blob/20eefea66fb541375124b4242f5bf3953c9980f9/manifests/params.pp#L94
https://github.com/djjudas21/puppet-freeradius/blob/20eefea66fb541375124b4242f5bf3953c9980f9/manifests/params.pp#L104

I'm using puppet agent with version 7.33.0 and puppetserver 8.6.3

**Comment by deligatedgeek** [comment]
This was fixed in [PR 230](https://github.com/djjudas21/puppet-freeradius/pull/230)
