### ISSUE TITLE
'netmask' field in client definitions is depricated in FR3

### ISSUE THREAD

**Issue by paulseward** [djjudas21/puppet-freeradius#23]
Tue Nov 24 10:47:54 2015 : Warning: 'netmask' field found in client testswitch is deprecated, use CIDR notation instead.  Please fix your configuration
Tue Nov 24 10:47:54 2015 : Warning: Support for 'netmask' will be removed in a future release

**Comment by djjudas21** [comment]
Fixed in 4c414f61fc81d91c492c04d996811008344dacec
