### ISSUE TITLE
Publish version 4.0.1 to Puppet forge.

### ISSUE THREAD

**Issue by benjamin-robertson** [djjudas21/puppet-freeradius#235]
Is there any chance of getting version 4.0.1 tagged and publish to the Puppet forge?

Need to have legacy facts removed for Puppet 8.

https://github.com/djjudas21/puppet-freeradius/pull/223/files

Along with this commit?
https://github.com/djjudas21/puppet-freeradius/commit/20eefea66fb541375124b4242f5bf3953c9980f9

Thanks

**Comment by djjudas21** [comment]
In principle I think this will be fine but I want @nward's feedback as I don't personally use this module in production any more :slightly_smiling_face:

**Comment by djjudas21** [comment]
I've tagged 4.0.1 as a pre-release https://github.com/djjudas21/puppet-freeradius/releases/tag/4.0.1 and this will automatically get published to Puppet Forge in this action: https://github.com/djjudas21/puppet-freeradius/actions/runs/11973776370

**Comment by benjamin-robertson** [comment]
Thanks
