### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by sts** [djjudas21/puppet-freeradius#46]
Restucturing the module could make the code cleaner and easier to read. Example branch below, would you be interested to incorporate such changes (without losing backwards compatibility?), although might remove support for puppet 3.x.

* https://github.com/sts/puppet-freeradius/tree/new/data/os
* `https://github.com/sts/puppet-freeradius/tree/new/manifests

**Comment by djjudas21** [comment]
I believe this has been addressed in v3.0.0
