### ISSUE TITLE
Directory permissions too tight

### ISSUE THREAD

**Issue by sts** [djjudas21/puppet-freeradius#53]
The permissions for a couple of directories are too tight, I think`/etc/raddb` and `/var/log/freeradus` can be relaxed to `0755`, as it circumvents using tab completion for the config files when working with sudo on systems.

**Comment by sts** [comment]
Commited to https://github.com/sts/puppet-freeradius/tree/fix_directory_modes

**Comment by djjudas21** [comment]
I agree that `/etc/raddb` can be relaxed but I'm not sure about the logs. Authentication logs are privileged information and you don't necessarily want to grant access to read those logs to everyone who has a shell account on the radius server.

At my employer, the logs are `0750` and privileged users get put in the `radiusd` group or use `sudo`. It is a bit annoying that you can't tab-complete, but it's necessary for security.

Can I suggest that the directory modes are exposed as a parameter and then every admin can set it to what they think is best for their site? The default should be `0750` so security is preserved and it's a conscious decision to open it up wider than that. Thanks :+1:

**Comment by djjudas21** [comment]
In fact `/etc/raddb` has privileged stuff in it too, as it contains shared secrets in client definitions, etc. So both these directory modes should be customisable via parameter.

**Comment by sts** [comment]
how are the mentioned files containing secrets/privileged stuff influenced by allowing directory traversal for normal users by adding the execute bit for directories only?

**Comment by djjudas21** [comment]
It would be OK to have the execute bit on directories, so long as the config files are `0640`

**Comment by sts** [comment]
Yes, thats what the pull request would do. Changes on my system:

`
Notice: /Stage[main]/Freeradius/File[/etc/freeradius]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[radiusd.conf]/mode: mode changed '0640' to '0644'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/statusclients.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/conf.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/attr.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/users.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/policy.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/dictionary.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/scripts]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/certs]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/clients.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/listen.d]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/sites-enabled]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/mods-enabled]/mode: mode changed '0750' to '0755'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/instantiate]/mode: mode changed '0750' to '0755'
`

`/var/log/freeradius` is untouched, and I think its not managed with this module anyways.

**Comment by djjudas21** [comment]
Well that looks fine. I'm happy to accept :+1:
