### ISSUE TITLE
init.pp: postrotate does not differ linux distributions

### ISSUE THREAD

**Issue by thtomate** [djjudas21/puppet-freeradius#80]
The config of logrotate does not take into account that the pid file is in /var/run/freeradius/freeradius.pid on Debian
postrotate    => 'kill -HUP `cat /var/run/radiusd/radiusd.pid`'

**Comment by djjudas21** [comment]
Thanks for reporting this. I'll look at it :+1:

**Comment by djjudas21** [comment]
I've just pushed a fix to the `pidfile` branch. Can you try that please? I'm just testing on CentOS but I don't have any Debian systems.
