### ISSUE TITLE
logrotate package dependency

### ISSUE THREAD

**Issue by craigulliott** [djjudas21/puppet-freeradius#81]
Hello, thanks for creating this module!

I got a little confused by the following error.

```
Evaluation Error: Error while evaluating a Function Call, Logrotate::Rule[wtmp]: rotate must be an integer at /etc/puppetlabs/code/environments/production/modules/logrotate/manifests/rule.pp:306:7 at /etc/puppetlabs/code/environments/production/modules/logrotate/manifests/defaults/debian.pp:16
```
I noted from the [puppet forge dependencies page](https://forge.puppet.com/jgazeley/freeradius/dependencies) that your module had a dependency on rodjek/logrotate. I added it manually in my Puppet file.

After some head scratching I looked at your metadata.json file and realized it was actually yo61/logrotate (which has now been migrated to puppet/logrotate). Switching to that package fixed the error.

I wanted to let you know incase others might go down the same hole.

Thanks again!

**Comment by djjudas21** [comment]
Sorry about that. We use `r10k` to deploy our Puppet code but it doesn't do any dependency resolution, so I hadn't noticed that the dependencies in `metadata.json` were out of date. I've now fixed this in 5a7c229 - thanks for letting me know!
