### ISSUE TITLE
Debian stretch

### ISSUE THREAD

**Issue by gavinlove** [djjudas21/puppet-freeradius#87]
Debian stretch was released in June now installs freeradius (3.0.12+dfsg-5+deb9u1)  as standard so will you be updating package this to support Debian 9?

https://packages.debian.org/stretch/arm64/freeradius

Thanks?

**Comment by djjudas21** [comment]
I'm happy to update the module metadata to say it supports Debian 9, if you can try it as-is and see if it works. There might be issues with things like paths, etc.

**Comment by thtomate** [comment]
I'm using it, I installed the package first by hand and the added it to host configuration. You just have to adopt the basepath, maybe turn ``preserve_mods`` off and should have an eye on logrotation.

**Comment by gavinlove** [comment]
Thank you both, I will try it when I can although this would be the first time I have setup freeradius so I might not pickup problems.

**Comment by djjudas21** [comment]
Good luck! FreeRADIUS is a complex beast and while this module tries to be helpful, it still has some sharp edges and assumes some knowledge of FreeRADIUS. You might find it helpful to join the [freeradius-users](http://lists.freeradius.org/mailman/listinfo/freeradius-users) mailing list. They're super knowledgeable.

**Comment by djjudas21** [comment]
@thtomate "adopt the basepath" - do you mean the default in this module is incorrect? Ideally I'd like to fix that - can you show me what you've had to override?

**Comment by davidc** [comment]
For some godunknown reason, they've moved it into /etc/freeradius/3.0 (without migrating old files and leaving them there to confuse the hell out of you).

**Comment by djjudas21** [comment]
I merged #95 which should address this issue by adding support... I will roll a new release

**Comment by djjudas21** [comment]
Tagged 3.6.0
