### ISSUE TITLE
Support for allow_expired_crl

### ISSUE THREAD

**Issue by fraserhess** [djjudas21/puppet-freeradius#90]
There is an undocumented boolean configuration option in the tls configuration of FreeRADIUS named `allow_expired_crl`. It's very helpful in the case that a CRL expires before it is replaced and FreeRADIUS is restarted. You can see it in the source code here: https://github.com/FreeRADIUS/freeradius-server/search?utf8=%E2%9C%93&q=allow_expired_crl&type=

Can you add support for `allow_expired_crl` in `freeradius::module::eap`?

**Comment by djjudas21** [comment]
Yay for undocumented options! I'm happy to add the option, although it might take me a while to do it as I'm quite busy at the moment.

Also, I'm sure you know already, but it sounds like a bad idea to use this option. I guess that's why it was never documented :smiley:

**Comment by djjudas21** [comment]
OK, I've just pushed a commit. Can you test this please and let me know if it works for you?

**Comment by fraserhess** [comment]
It works for me. Thank you. 

In eap.erb, should the comment `# Allow use of expired CRLs` be inside the conditional right below it?

**Comment by djjudas21** [comment]
Good spot. Looks like there's actually a few comments like this - I'll fix them

**Comment by djjudas21** [comment]
Right, I've moved all the comments inside the conditionals in e5822c6
